version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  nats:
    image: nats:2.10
    container_name: nats_server
    ports:
      - "4222:4222" # client port
      - "8222:8222" # http monitoring
    networks:
      - app-network
    command: "-js" # Enable JetStream
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
