server:
  port: 8888

spring:
  application:
    name: phoca
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: "SELECT key, value FROM properties WHERE application = ? AND profile = ? AND label = ?"
    bus:
      enabled: true
      id: ${spring.application.name}
      destination: "config-bus"
      nats:
        server-url: "nats://localhost:4222"
        destination: "config-bus"
  datasource:
    url: jdbc:postgresql://localhost:5432/phoca_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

# gRPC server port
grpc:
  server:
    port: 9090
