server:
  port: 8080

# This will be overridden by the config from the config server
password:
  policy:
    min-length: 8
    require-uppercase: true
    require-lowercase: true
    require-numbers: true
    require-special: false

spring:
  application:
    name: pusa
  grpc:
    client:
      default-channel:
        address: 'static://localhost:9090'
        enable-keep-alive: true
        negotiation-type: plaintext
  config:
    import: "configserver:http://127.0.0.1:8888"
  cloud:
    config:
      label: "1.0"
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 30
        max-interval: 3000
    bus:
      enabled: true
      id: ${spring.application.name}
      destination: "config-bus" # Same destination as phoca
      nats:
        server-url: "nats://localhost:4222"
        destination: "config-bus"
  datasource:
    url: jdbc:postgresql://localhost:5432/pusa_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: "refresh,busrefresh,health"
